/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Color, Depth, Fresnel, LayerMaterial } from "lamina";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

export default function Logo(props) {
  const mesh = useRef();
  const depth = useRef();
  const meshb = useRef();

  const { nodes, materials } = useGLTF("./LogoExport2.glb");

  useFrame((state, delta) => {
    mesh.current.rotation.z += delta / 2;
    depth.current.origin.set(-state.mouse.y, state.mouse.x, 0);

    meshb.current.rotation.x =
      meshb.current.rotation.y =
      meshb.current.rotation.z +=
        delta;
  });
  return (
    <group {...props} dispose={null}>
      <mesh
        rotation-y={Math.PI / 2}
        ref={mesh}
        geometry={nodes.Cube.geometry}
        material={materials.Material}
        scale={0.5}
      >
        <LayerMaterial>
          <Color color="#ff4eb8" alpha={1} mode="normal" />
          <Depth
            colorA="#ff8f00"
            colorB="#00ffff"
            alpha={0.5}
            mode="normal"
            near={0}
            far={3}
            origin={[1, 1, 1]}
          />
          <Depth
            ref={depth}
            colorA="#ff8f00"
            colorB="black"
            alpha={1}
            mode="lighten"
            near={0.25}
            far={2}
            origin={[1, 0, 0]}
          />
          <Fresnel
            mode="softlight"
            color="white"
            intensity={0.3}
            power={2}
            bias={0}
          />
        </LayerMaterial>
      </mesh>
      <mesh
        ref={meshb}
        geometry={nodes.Sphere.geometry}
        material={nodes.Sphere.material}
      >
        <LayerMaterial attach="material" side={THREE.BackSide}>
          <Color color="#ff4eb8" alpha={1} mode="normal" />
          <Depth
            colorA="#ff8f00"
            colorB="#00ffff"
            alpha={0.5}
            mode="normal"
            near={0}
            far={300}
            origin={[100, 100, 100]}
          />
        </LayerMaterial>
      </mesh>
    </group>
  );
}

useGLTF.preload("./LogoExport2.glb");
